apiVersion: v1
kind: Pod
metadata:
    name: centos-pod
    labels:
        tier: front-end
spec:
    containers:
    - name: centos-container
      image: centos
      args:
      - /bin/sh
      - -c
      - sleep 5000
