apiVersion: apps/v1
kind: ReplicaSet
metadata:
	name: rs-appjs
spec:
	replicas: 1
	selector:
		matchLabels:
			app: appjs
	template:
		metadata:
			app: appjs
		spec:
			containers:
			- name: appjs-container
			  image: smlinux/appjs
			ports:
			- containerPort: 8080
