apiVersion: v1
kind: Pod
metadata:
    name: mongodb-pod
spec:
    containers:
    - name: mongo-container
      image: mongo
      ports:
      - containerPort: 27017
        protocol: TCP
      volumeMounts:
      - name: dbdata
        mountPath: /data/db
    volumes:
    - name: dbdata
      persistentVolumeClaim:
        claimName: mongo-pvc
