apiVersion: v1
kind: Pod
metadata:
    name: pod
spec:
    containers:
    - name: container-name
      image: image
      volumeMounts:
      - name: volume-name
        mountPath: /mount/dir
    volumes:
    - name: volume-name
      persistentVolumeClaim:
        claimName: pvc-name
