apiVersion: v1
kind: Pod
metadata:
    name: dynamic-web
spec:
    containers:
    - name: web-generator
      image: smlinux/cowsay-web
      volumeMounts:
      - name: html
        mountPath: /webdata
    - name: web-server
      image: nginx:1.14
      ports:
      - containerPort: 80
      volumeMounts:
      - name: html
        mountPath: /usr/share/nginx/html
        readOnly: true
    volumes:
    - name: html
      emptyDir: {}
