apiVersion: v1
kind: Pod
metadata:
    name: limited-pod
spec:
    containers:
    - name: main
      image: busybox
      command: ['dd', 'if=/dev/zero', 'of=/dev/null']
      resources:
        requests:
            cpu: 200m
            memory: 500Mi
